# Generated by Django 5.1.4 on 2025-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emai',
            new_name='email',
        ),
    ]
